version: "3"
networks:
  skema_net:
    external: true

services:
    scienceparse:
        image: allenai/scienceparse:2.0.3
        ports:
            - "8080:8080"
        networks:
            skema_net:
                aliases:
                    - "scienceparse"  # use ${AGENT_NAME} before deploying

    grobidquantities:
        build: ./quantities
        image: clulab/quantities:latest
        ports:
            - "8060:8060"
        networks:
            skema_net:
                aliases:
                    - "grobidquantities"  # use ${AGENT_NAME} before deploying
