.drone.yml
skema/skema-rs/
skema/text_reading/
!/skema/text_reading/mention_linking
Dockerfile.*
docker-compose.*

skema/program_analysis/CAST/fortran/tree-sitter-fortran/

**/__pycache__/
build/
docs/
*.pyc
*.egg-info
