# Docker Compose file to launch the MemgraphDB platform standalone.
version: "3"

networks:
  skema_net:
    external: true

services:
  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]
    networks:
      skema_net:
        aliases:
          - "skema_database_1" # use ${AGENT_NAME} before deploying

volumes:
  mg_lib:
  mg_log:
  mg_etc:
