# Docker Compose file to launch multiple SKEMA services in conjuction.
# Currently, this file launches the skema-py and skema-rs services.
# Change port mappings appropriately before deploying to avoid clashes.
# The format for the port mapping specification goes like this:
# HOST_PORT:CONTAINER_PORT.
version: "3"


networks:
  skema_net:
    external: true

services:
  # The skema-py web service exposing functionality implemented in Python.
  skema-py:
    image: skema-py:latest
    build:
      context: .
      dockerfile: Dockerfile.skema-py
    container_name: skema-py
    ports:
    - "8001:8000"
    command: ["uvicorn", "server:app", "--host", "0.0.0.0"]
    networks:
      skema_net:
        aliases:
          - "skema-py"  # use ${AGENT_NAME} before deploying


  # The skema-rs web service exposing functionality implemented in Rust.
  skema-rs:
    build:
      context: .
      dockerfile: Dockerfile.skema-rs
    entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
    ports:
      - "8080:8080"
    networks:
      skema_net:
        aliases:
          - "skema-rs"  # use ${AGENT_NAME} before deploying



  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]
    networks:
      skema_net:
        aliases:
          - "skema_database_1"  # use ${AGENT_NAME} before deploying


volumes:
  mg_lib:
  mg_log:
  mg_etc:
