.drone.yml
skema/skema-rs/
skema/text_reading/
!/skema/text_reading/python
Dockerfile.*
docker-compose.*

skema/program_analysis/TS2CAST/tree-sitter-fortran/

**/__pycache__/
build/
docs/
*.pyc
*.egg-info
