# Docker Compose file for the skema-rs web service
version: "3"


networks:
  skema_net:
    external: true

services:
  # The skema-rs web service exposing functionality implemented in Rust.
  skema-rs:
    build:
      context: .
      dockerfile: Dockerfile.skema-rs
    entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
    ports:
      - "8080:8080"
    networks:
      skema_net:
        aliases:
          - "img2mml"  # use ${AGENT_NAME} before deploying


  # We currently use Memgraph (in-memory graph database).
  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]

volumes:
  mg_lib:
  mg_log:
  mg_etc:
