from rust:1.70

# =====================
# ENV setup for app
# =====================
ARG APP_VERSION=unknown
ENV APP_VERSION=$APP_VERSION

run apt update \
    && apt install -y \
        cmake openssl libclang-13-dev

workdir /usr/src/myapp
copy skema/skema-rs .
run cargo build --release --bin skema_service
