# Docker Compose file for the img2mml service
version: "3"
services:
  img2mml:
    image: img2mml:latest
    build:
      context: .
      dockerfile: Dockerfile.img2mml
    entrypoint: uvicorn img2mml:app --host=0.0.0.0 --reload
    ports:
      - "8000:8000"
