# Docker Compose file for the Code2FN service
version: "3.9"

services:
  Code2FN:
    image: code2fn:latest
    build:
      context: .
      dockerfile: Dockerfile.code2fn
    container_name: Code2FN
    ports:
    - "8000:8000" # Change port mapping appropriately before deploying.
    command: ["uvicorn", "server:app", "--host", "0.0.0.0"]
