#!/usr/bin/env python3

# build the tree-sitter MatLab shared object file

import os.path
import subprocess
import shutil
from tree_sitter import Language

# Determine the caller path
CALLER_PATH = os.getcwd()

# Determine absolute path of this file
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

# Move to project directory
os.chdir(PROJECT_PATH)

# Create the tree-sitter grammar 
ret = subprocess.call('tree-sitter generate', shell = True)
shutil.copy('scanner.c', 'src/scanner.c')

if(ret):

    LANGUAGE_LIBRARY_REL_PATH = os.path.join("build", "matlab.so")

    Language.build_library(
        # Store the library in the `build` directory
        LANGUAGE_LIBRARY_REL_PATH,
        # Include one or more languages
        ["matlab"],
    )

    subprocess.call('cp scanner.c src/scanner.c', shell = True)


# Return to caller directory
os.chdir(CALLER_PATH)
