# Docker Compose file for the SKEMA web service
version: "3"
services:
  # The SKEMA web service exposing functionality implemented in Rust.
  skema:
    build: 
      dockerfile: Dockerfile #TODO: Is there a better way to do this?
      context: ../
    entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
    ports:
      - "8080:8080"

  # We currently use Memgraph (in-memory graph database).
  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]

  # Python endpoints for Skema service
  endpoints:
    build: .
    ports: 
      - "8000:8000"
    environment:
      - SKEMA_HOST=${SKEMA_HOST}
      - SKEMA_PORT=${SKEMA_PORT}
    entrypoint: uvicorn server:app --reload --host 0.0.0.0

volumes:
  mg_lib:
  mg_log:
  mg_etc:
