openapi: 3.0.0
info:
  version: "1.0.6"
  title: SEC Reader API
  description: RESTful API exposing core functionality of sec reader.
  contact:
    email: ghp@lum.ai
servers:
 - url: /api/document
tags:
  - name: "sec"
    description: |
      Operations specific to SEC project.
  - name: "config"
    description: |
      Endpoints for inspecting project config.

paths:
  /buildinfo:
    get:
      tags:
        - "config"
      summary: Information about the current version of this app.
      description: Provides detailed build information about the currently running app.
      operationId: buildinfo
      parameters:
        - name: pretty
          in: query
          description: |
            Whether or not to pretty print the response.
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: "A JSON object containing build information."
          content:
            application/json:
              schema:
                type: string

components:
  schemas:

    Document:
      type: object
      required:
        - id
        - text
        - sentences
      properties:
        id:
          type: integer
          format: int64
          description: |
            The equivalence hash for this org.clulab.processors.Document.
        text:
          type: string
          description: |
            The original text from which this Document was produced.
        sentences:
          type: array
          description: |
            array of org.clulab.processors.Sentence.
          items:
            $ref: "#/components/schemas/Sentence"

    Sentence:
      type: object
      required:
        - words
        - startOffsets
        - endOffsets
  #      - raw
  #      - tags
  #      - lemmas
  #      - entities
  #      - norms
  #      - chunks
        - graphs
      properties:
        words:
          type: array
          description: |
            The tokens for this sentence.
          items:
            type: string
        lemmas:
          type: array
          description: |
            The lemma form of each token in this sentence.
          items:
            type: string
        tags:
          type: array
          description: |
            The part of speech tag for each token in this sentence.
          items:
            type: string
        chunks:
          type: array
          description: |
            The BIO-style chunk label designating a coarse XP assignment for each token in this sentence.
          items:
            type: string
        entities:
          type: array
          description: |
            The BIO-style entity label for each token in this sentence.
          items:
            type: string
        startOffsets:
          type: array
          description: |
            The character-based start offset for each token in this sentence.
          items:
            type: integer
            format: int32
        endOffsets:
          type: array
          description: |
            The character-based end offset for each token in this sentence.
          items:
            type: integer
            format: int32
        graphs:
          $ref: "#/components/schemas/GraphMap"

    GraphMap:
      type: object
      description: |
        Map of graph name -> DirectedGraph.
      additionalProperties:
        type: string
        description: |
          The name of a DirectedGraph.

    DirectedGraph:
      type: object
      properties:
        edges:
          type: array
          description: |
            A edges comprising this graph.
          items:
            $ref: "#/components/schemas/Edge"
        roots:
          type: array
          description: |
            The token indices corresponding to the root nodes for this DirectedGraph.
          items:
            type: integer
            format: int32

    Edge:
      type: object
      required:
        - source
        - destination
        - relation
      properties:
        source:
          type: integer
          format: int32
          description: |
            The token index for the source vertex.
        destination:
          type: integer
          format: int32
          description: |
            The token index for the destination vertex.
        relation:
          type: string
          description: |
            The relation to which this Edge corresponds.
    Interval:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: integer
          format: int32
          description: |
            Inclusive start of org.clulab.struct.Interval.
        end:
          type: integer
          format: int32
          description: |
            Exclusive end of org.clulab.struct.Interval.

    Argument:
      type: object
      required:
        - role
        - text
        - subtype
        - labels
      properties:
        role:
          type: string
          description: |
            The argument's role (ex. theme)
        text:
          type: string
          description: |
            The text (span) corresponding to this argument
        subtype:
          type: string
          description: |
            Lowest hyponym in the labels array
        labels:
          type: array
          description: |
            array of Mention labels
          items: string

    MentionData:
      type: object
      required:
        - documents
        - mentions
      properties:
        documents:
          type: object
          description: |
            Map from equivalence hash to org.clulab.processors.Document.
          additionalProperties:
            type: integer
            format: int64
        mentions:
          type: array
          description: |
            array of org.clulab.odin.Mention.
          items:
            $ref: "#/components/schemas/Mention"

    Mention:
      type: object
      required:
        - type
        - id
        - text
        - labels
        - tokenInterval
        - characterStartOffset
        - characterEndOffset
        - sentence
        - document
        - keep
        - foundBy

      properties:
        type:
          type: array
          description: |
            A code denoting the type of this mention.
          items:
            enum: ["TextBoundMention", "EventMention", "RelationMention", "CrossSentenceMention"]
        id:
          type: string
          description: |
            Equivalence identifier of the form `shortCode:equivalenceHash`.  `shortCode` is expected to be one of the following: ["T", "E", "R", "CS"].
        text:
          type: string
          description: |
            Enclosing text span corresponding to this Mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        tokenInterval:
          $ref: "#/components/schemas/Interval"
        characterStartOffset:
          type: integer
          format: int32
        characterEndOffset:
          type: integer
          format: int32
        sentence:
          type: integer
          format: int32
          description: |
            The sentence index for the org.clulab.processors.Sentence matching the referenced org.clulab.processors.Document.
        document:
          type: integer
          format: int64
          description: |
            The ID corresponding to the document referenced in the `documents` property of `MentionData`.
        keep:
          type: boolean
          description: |
            Whether or not the Mention was intended to be retained.
        foundBy:
          type: string
          description: |
            The name of the rule responsible for detecting this mention.

    SimpleMentionData:
      type:
        type: array
        description: |
          A sequence of simplified Odin Mentions
        items:
            oneOf:
              - $ref: '#/components/schemas/SimpleTextBoundMention'
              - $ref: '#/components/schemas/SimpleRelationMention'
              - $ref: '#/components/schemas/SimpleEventMention'
              - $ref: '#/components/schemas/SimpleCrossSentenceMention'

    SimpleTextBoundMention:
      type: object
      required:
        - $type
        - "doc-id"
        - sentence
        - "sentence-index"
        - labels
        - span
        - found-by

      properties:
        $type:
          type: string
          description: |
            An identifier for this mention type.
          items:
            enum: ["textbound"]
        "doc-id":
          type: string
          description: |
            An identifier for the source document from which this mention originates.
        text:
          type: string
          description: |
            Enclosing text span corresponding to this mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        sentence:
          type: string
          description: |
            The sentence text that encompasses this mention.
        "sentence-index":
          type: integer
          format: int32
          description: |
            The index for this sentence (i.e., its order within the document)
        found-by:
          type: string
          description: |
            The name of the rule responsible for detecting this mention.

    SimpleRelationMention:
      type: object
      required:
        - $type
        - "doc-id"
        - sentence
        - "sentence-index"
        - labels
        - span
        - found-by
        - arguments

      properties:
        $type:
          type: string
          description: |
            An identifier for this mention type.
          items:
            enum: ["relation"]
        "doc-id":
          type: string
          description: |
            An identifier for the source document from which this mention originates.
        text:
          type: string
          description: |
            Enclosing text span corresponding to this mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        sentence:
          type: string
          description: |
            The sentence text that encompasses this mention.
        "sentence-index":
          type: integer
          format: int32
          description: |
            The index for this sentence (i.e., its order within the document)
        "found-by":
          type: string
          description: |
            The name of the rule responsible for detecting this mention.
        arguments:
          $ref: '#/components/schemas/SimpleArgumentsMap'
    
    SimpleEventMention:
      type: object
      required:
        - $type
        - "doc-id"
        - sentence
        - "sentence-index"
        - labels
        - span
        - found-by
        - arguments
        - trigger

      properties:
        $type:
          type: string
          description: |
            An identifier for this mention type.
          items:
            enum: ["event"]
        "doc-id":
          type: string
          description: |
            An identifier for the source document from which this mention originates.
        text:
          type: string
          description: |
            Enclosing text span corresponding to this mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        sentence:
          type: string
          description: |
            The sentence text that encompasses this mention.
        "sentence-index":
          type: integer
          format: int32
          description: |
            The index for this sentence (i.e., its order within the document)
        "found-by":
          type: string
          description: |
            The name of the rule responsible for detecting this mention.
        arguments:
          $ref: '#/components/schemas/SimpleArgumentsMap'
        trigger:
          type: string
          description: |
            A predicate that signals this particular relation.

    SimpleCrossSentenceMention:
      type: object
      required:
        - $type
        - "doc-id"
        - sentence
        - "sentence-index"
        - labels
        - span
        - "found-by"
        - arguments
        - anchor
        - "anchor-sentence"
        - "anchor-sentence-index"
        - neighbor
        - "neighbor-sentence"
        - "neighbor-sentence-index"

      properties:
        $type:
          type: string
          description: |
            An identifier for this mention type.
          items:
            enum: ["cross-sentence"]
        "doc-id":
          type: string
          description: |
            An identifier for the source document from which this mention originates.
        text:
          type: string
          description: |
            Enclosing text span corresponding to this mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        sentence:
          type: string
          description: |
            The sentence text that encompasses this mention.
        "sentence-index":
          type: integer
          format: int32
          description: |
            The index for this sentence (i.e., its order within the document)
        "found-by":
          type: string
          description: |
            The name of the rule responsible for detecting this mention.
        arguments:
          $ref: '#/components/schemas/SimpleArgumentsMap'
        anchor:
          type: string
          description: |
            A component mention falling in a different sentence from the neighbor mention.
        "anchor-sentence":
          type: string
          description: |
            The sentence text that encompasses this anchor mention.
        "anchor-sentence-index":
          type: integer
          format: int32
          description: |
            The anchor sentence's index for this sentence (i.e., its order within the document)
        neighbor:
          type: string
          description: |
            A component mention falling in different sentence from the anchor mention.
        "neighbor-sentence":
          type: string
          description: |
            The sentence text that encompasses this neighbor mention.
        "neighbor-sentence-index":
          type: integer
          format: int32
          description: |
            The index for this sentence (i.e., its order within the document)
    
    SimpleArgumentsMap:
        type: object
        additionalProperties:
          type: array
          description: |
            array of simplified arguments
          items:
            $ref: "#/components/schemas/SimpleArgument"

    SimpleArgument:
        type: object
        required:
          - text
          - labels
        properties:
          text:
            type: string
            description: |
              The text of this argument
          labels:
            type: array
            description: |
              Array of mention labels for this argument
            items: string
            