#!/bin/sh
# Shell utility to run the cosmos annotation app with default values

# Copy the json files to the intermediate directory
cp /data/inputs/*.json /data/json_inputs/

# Convert parquet to jsons
python3 cosmos_integration.py -o /data/json_inputs /data/inputs

# Run the TR pipeline
java -jar target/scala-2.12/skema_text_reading-assembly-0.1.0-SNAPSHOT.jar org.ml4ai.skema.text_reading.apps.AnnotateCosmosJsonFiles -o /data/outputs /data/json_inputs