#!/bin/sh
# Shell utility to run the cosmos annotation app with default values
usage() { echo "Usage: $0 [-i <input path>] [-o <output path>] [-j <json_input path>]" 1>&2; exit 1; }

while getopts ":i:o:j:" x; do
    case "${x}" in
        i)
            input=${OPTARG}
            ;;
        o)
            output=${OPTARG}
            ;;
        j)
            json_input=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

if [ -z "${input}" ] || [ -z "${output}" ] || [ -z "${json_input}" ]; then
    usage
fi


# Copy the json files to the intermediate directory
cp ${input}/*.json ${json_input}

# Convert parquet to jsons
python3 cosmos_integration.py -o ${json_input} ${input}

# Run the TR pipeline
java -jar target/scala-2.12/skema_text_reading-assembly-0.1.0-SNAPSHOT.jar org.ml4ai.skema.text_reading.apps.AnnotateCosmosJsonFiles -o ${output} ${json_input}
