#!/usr/bin/env python3

# Clone, build, and test the treesitter matlab grammar

import os.path
import subprocess
import shutil
from tree_sitter import Language

MATLAB_CLONE_URL = 'https://github.com/acristoffers/tree-sitter-matlab.git'
MATLAB_TEST_CORPUS_URL = 'https://github.com/mathworks/MATLAB-Language-grammar.git' 


# Determine the caller path
CALLER_PATH = os.getcwd()

# Determine absolute path of this file
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

def clone(git_url):

    # Remove the repo from local filesystem if it exists
    clone_dir = git_url.split('/')[-1].split('.git')[0]
    print('Cleaning ' + clone_dir)
    ret = subprocess.run(['rm', '-rf', clone_dir])

    # Clone the tree-sitter matlab grammar 
    print('Cloning ' + git_url)
    ret = subprocess.run(['git', 'clone', git_url])

    if(ret):
        print('Clone succeeded')
    else:
        print('Clone failed')
    return ret

def main():
    # Move to project directory
    os.chdir(PROJECT_PATH)
    # Clone the tree-sitter matlab grammar 
    clone(MATLAB_CLONE_URL)
    # Clone the tree-sitter matlab grammar 
    clone(MATLAB_TEST_CORPUS_URL)
    # Return to caller directory
    os.chdir(CALLER_PATH)

if __name__ == "__main__":
    main()
