#!/usr/bin/env python3
import json
import sys
from skema.program_analysis.CAST.matlab.matlab_to_cast import MatlabToCast


def show_cast(filename):
    """ Run a file of any type through the Tree-sitter MATLAB parser"""
    parser = MatlabToCast(filename)
    print("\n\nINPUT:")
    print(parser.filename)
    print("\nSOURCE:")
    print(parser.source)
    print('\nCAST:')
    cast_list = parser.out_cast
    for cast in cast_list:
        jd = json.dumps(
            cast.to_json_object(),
            sort_keys=True,
            indent=2,
        )
        print(jd)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        for i in range(1, len(sys.argv)):
            show_cast(sys.argv[i])
    else:
        print("Please enter one filename to parse")

