""" all the tokens from the Waterloo model syntax tree """

""" Waterloo model syntax keywords """
KEYWORDS = [
    # keywords we currently support
    'arguments',
    'assignment',
    'binary_operator',
    'block',
    'boolean',
    'boolean_operator',
    'case',
    'case_clause',
    'cell',
    'command',
    'command_argument',
    'command_name',
    'comment',
    'comparison_operator',
    'else',
    'else_clause',
    'elseif',
    'elseif_clause',
    'end',
    'function',
    'function_arguments',
    'function_call',
    'function_definition',
    'identifier',
    'if',
    'if_statement',
    'matrix',
    'module'
    'not_operator',
    'number',
    'otherwise',
    'otherwise_clause',
    'parenthesis',
    'postfix_operator',
    'row',
    'source_file',
    'spread_operator',
    'string',
    'string_content',
    'switch',
    'switch_statement',
    'unary_operator',

    # keywords to be supported
    'break_statement',
    'continue_statement',
    'field_expression',
    'for',
    'for_statement',
    'function_output',
    'iterator',
    'lambda',
    'line_continuation',
    'multioutput_variable',
    'range',
    'while',
    'while_statement'
]

""" anything not a keyword """
OTHER_TOKENS = [
    '\"',
    '&',
    '&&',
    '\'',
    '(',
    ')',
    '*',
    '+',
    ',',
    '-',
    '.',
    '.*',
    './',
    '/',
    ':',
    ';',
    '<',
    '<=',
    '=',
    '==',
    '>',
    '>=',
    '@',
    '[',
    ']',
    '{',
    '||',
    '}',
    '~'
]

""" all tokens """
TOKENS = KEYWORDS + OTHER_TOKENS
