eqn_src = [
  {
    id: "08160e6f-a4c0-4ca9-88cc-7b5febd58bf8",
    mathml:
      '<math xmlns="http://www.w3.org/1998/Math/MathML">\n  <mi>u</mi>\n  <mrow data-mjx-texclass="INNER">\n    <mo data-mjx-texclass="OPEN">(</mo>\n    <msub>\n      <mi>t</mi>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </msub>\n    <mo data-mjx-texclass="CLOSE">)</mo>\n  </mrow>\n  <mo>=</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>p</mi>\n    </mrow>\n  </msub>\n  <mi>e</mi>\n  <mrow data-mjx-texclass="INNER">\n    <mo data-mjx-texclass="OPEN">(</mo>\n    <msub>\n      <mi>t</mi>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </msub>\n    <mo data-mjx-texclass="CLOSE">)</mo>\n  </mrow>\n  <mo>+</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>i</mi>\n    </mrow>\n  </msub>\n  <mrow data-mjx-texclass="INNER">\n    <mo data-mjx-texclass="OPEN">(</mo>\n    <munderover>\n      <mo data-mjx-texclass="OP">\u2211</mo>\n      <mrow>\n        <mi>j</mi>\n        <mo>=</mo>\n        <mn>0</mn>\n      </mrow>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </munderover>\n    <mi>e</mi>\n    <mrow data-mjx-texclass="INNER">\n      <mo data-mjx-texclass="OPEN">(</mo>\n      <msub>\n        <mi>t</mi>\n        <mrow>\n          <mi>j</mi>\n        </mrow>\n      </msub>\n      <mo data-mjx-texclass="CLOSE">)</mo>\n    </mrow>\n    <mi mathvariant="normal">\u0394</mi>\n    <mi>t</mi>\n    <mo data-mjx-texclass="CLOSE">)</mo>\n  </mrow>\n  <mo>+</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>d</mi>\n    </mrow>\n  </msub>\n  <mrow data-mjx-texclass="INNER">\n    <mo data-mjx-texclass="OPEN">(</mo>\n    <mfrac>\n      <mrow>\n        <mi>e</mi>\n        <mrow data-mjx-texclass="INNER">\n          <mo data-mjx-texclass="OPEN">(</mo>\n          <msub>\n            <mi>t</mi>\n            <mrow>\n              <mi>n</mi>\n            </mrow>\n          </msub>\n          <mo data-mjx-texclass="CLOSE">)</mo>\n        </mrow>\n        <mo>\u2212</mo>\n        <mi>e</mi>\n        <mrow data-mjx-texclass="INNER">\n          <mo data-mjx-texclass="OPEN">(</mo>\n          <msub>\n            <mi>t</mi>\n            <mrow>\n              <mi>n</mi>\n              <mo>\u2212</mo>\n              <mn>1</mn>\n            </mrow>\n          </msub>\n          <mo data-mjx-texclass="CLOSE">)</mo>\n        </mrow>\n      </mrow>\n      <mrow>\n        <mi mathvariant="normal">\u0394</mi>\n        <mi>t</mi>\n      </mrow>\n    </mfrac>\n    <mo data-mjx-texclass="CLOSE">)</mo>\n  </mrow>\n</math>',
    latex:
      "u\\left(t_{n}\\right)=K_{p} e\\left(t_{n}\\right)+K_{i}\\left(\\sum_{j=0}^{n} e\\left(t_{j}\\right) \\Delta t\\right)+K_{d}\\left(\\frac{e\\left(t_{n}\\right)-e\\left(t_{n-1}\\right)}{\\Delta t}\\right)",
  },
];
