eqn_src = [
    {
        "id": "08160e6f-a4c0-4ca9-88cc-7b5febd58bf8",
        "mathml": "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>u</mi>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <msub>\n      <mi>t</mi>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </msub>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n  <mo>=</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>p</mi>\n    </mrow>\n  </msub>\n  <mi>e</mi>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <msub>\n      <mi>t</mi>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </msub>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n  <mo>+</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>i</mi>\n    </mrow>\n  </msub>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <munderover>\n      <mo data-mjx-texclass=\"OP\">\u2211</mo>\n      <mrow>\n        <mi>j</mi>\n        <mo>=</mo>\n        <mn>0</mn>\n      </mrow>\n      <mrow>\n        <mi>n</mi>\n      </mrow>\n    </munderover>\n    <mi>e</mi>\n    <mrow data-mjx-texclass=\"INNER\">\n      <mo data-mjx-texclass=\"OPEN\">(</mo>\n      <msub>\n        <mi>t</mi>\n        <mrow>\n          <mi>j</mi>\n        </mrow>\n      </msub>\n      <mo data-mjx-texclass=\"CLOSE\">)</mo>\n    </mrow>\n    <mi mathvariant=\"normal\">\u0394</mi>\n    <mi>t</mi>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n  <mo>+</mo>\n  <msub>\n    <mi>K</mi>\n    <mrow>\n      <mi>d</mi>\n    </mrow>\n  </msub>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <mfrac>\n      <mrow>\n        <mi>e</mi>\n        <mrow data-mjx-texclass=\"INNER\">\n          <mo data-mjx-texclass=\"OPEN\">(</mo>\n          <msub>\n            <mi>t</mi>\n            <mrow>\n              <mi>n</mi>\n            </mrow>\n          </msub>\n          <mo data-mjx-texclass=\"CLOSE\">)</mo>\n        </mrow>\n        <mo>\u2212</mo>\n        <mi>e</mi>\n        <mrow data-mjx-texclass=\"INNER\">\n          <mo data-mjx-texclass=\"OPEN\">(</mo>\n          <msub>\n            <mi>t</mi>\n            <mrow>\n              <mi>n</mi>\n              <mo>\u2212</mo>\n              <mn>1</mn>\n            </mrow>\n          </msub>\n          <mo data-mjx-texclass=\"CLOSE\">)</mo>\n        </mrow>\n      </mrow>\n      <mrow>\n        <mi mathvariant=\"normal\">\u0394</mi>\n        <mi>t</mi>\n      </mrow>\n    </mfrac>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n</math>",
        "latex": "u\\left(t_{n}\\right)=K_{p} e\\left(t_{n}\\right)+K_{i}\\left(\\sum_{j=0}^{n} e\\left(t_{j}\\right) \\Delta t\\right)+K_{d}\\left(\\frac{e\\left(t_{n}\\right)-e\\left(t_{n-1}\\right)}{\\Delta t}\\right)"
    },
    {
        "id": "186a42c3-c8e5-4902-bc8f-39e4759853a3",
        "mathml": "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mfrac>\n    <msubsup>\n      <mi>I</mi>\n      <mrow>\n        <mi>i</mi>\n        <mo>,</mo>\n        <mi>t</mi>\n      </mrow>\n      <mrow>\n        <mi>i</mi>\n        <mi>n</mi>\n        <mi>c</mi>\n      </mrow>\n    </msubsup>\n    <msub>\n      <mi>M</mi>\n      <mrow>\n        <mi>i</mi>\n        <mo>,</mo>\n        <mi>t</mi>\n      </mrow>\n    </msub>\n  </mfrac>\n  <mo>=</mo>\n  <mfrac>\n    <msub>\n      <mi>U</mi>\n      <mrow>\n        <mi>c</mi>\n        <mo>,</mo>\n        <mi>t</mi>\n      </mrow>\n    </msub>\n    <mrow>\n      <msub>\n        <mi>N</mi>\n        <mrow>\n          <mi>c</mi>\n        </mrow>\n      </msub>\n      <mo>\u2212</mo>\n      <msub>\n        <mrow>\n          <mover>\n            <mi>R</mi>\n            <mo stretchy=\"false\">^</mo>\n          </mover>\n        </mrow>\n        <mrow>\n          <mi>c</mi>\n          <mo>,</mo>\n          <mi>t</mi>\n        </mrow>\n      </msub>\n    </mrow>\n  </mfrac>\n  <mstyle scriptlevel=\"0\">\n    <mspace width=\"1em\"></mspace>\n  </mstyle>\n</math> <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>t</mi>\n  <mo>\u2208</mo>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">[</mo>\n    <msub>\n      <mi>T</mi>\n      <mrow>\n        <mn>0</mn>\n      </mrow>\n    </msub>\n    <mo>,</mo>\n    <msub>\n      <mi>T</mi>\n      <mrow>\n        <mn>1</mn>\n      </mrow>\n    </msub>\n    <mo data-mjx-texclass=\"CLOSE\">]</mo>\n  </mrow>\n</math> <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>i</mi>\n</math> <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>c</mi>\n</math>",
        "latex": "\\frac{I_{i, t}^{i n c}}{M_{i, t}}=\\frac{U_{c, t}}{N_{c}-\\hat{R}_{c, t}} \\quad t \\in\\left[T_{0}, T_{1}\\right] i c"
    },
    {
        "id": "f8feb3d9-ea19-45c4-8d1c-bbbc93fe3f18",
        "mathml": "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>\u03b3</mi>\n  <mo stretchy=\"false\">(</mo>\n  <mi>t</mi>\n  <mo stretchy=\"false\">)</mo>\n  <mo>=</mo>\n  <mfrac>\n    <mn>1</mn>\n    <mrow>\n      <mi>\u03ba</mi>\n      <mo stretchy=\"false\">(</mo>\n      <mi>t</mi>\n      <mo stretchy=\"false\">)</mo>\n    </mrow>\n  </mfrac>\n  <mo>=</mo>\n  <mfrac>\n    <mi>d</mi>\n    <mrow>\n      <mi>d</mi>\n      <mi>t</mi>\n    </mrow>\n  </mfrac>\n  <mi>C</mi>\n  <mo stretchy=\"false\">(</mo>\n  <mi>t</mi>\n  <mo stretchy=\"false\">)</mo>\n</math>",
        "latex": "\\gamma(t)=\\frac{1}{\\kappa(t)}=\\frac{d}{d t} C(t)"
    },
    {
        "id": "28b7e421-3929-4130-8db8-8a27a411b51c",
        "mathml": "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mi>p</mi>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <mi mathvariant=\"bold-italic\">I</mi>\n    <mo>,</mo>\n    <msup>\n      <mi mathvariant=\"bold-italic\">R</mi>\n      <mrow>\n        <mo>+</mo>\n      </mrow>\n    </msup>\n    <mo>\u2223</mo>\n    <mrow>\n      <mi data-mjx-variant=\"-tex-calligraphic\" mathvariant=\"script\">R</mi>\n    </mrow>\n    <mo>,</mo>\n    <mi mathvariant=\"bold-italic\">n</mi>\n    <mo>,</mo>\n    <mi mathvariant=\"bold-italic\">N</mi>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n  <mo>=</mo>\n  <mi>p</mi>\n  <mo stretchy=\"false\">(</mo>\n  <mi mathvariant=\"bold-italic\">I</mi>\n  <mo>\u2223</mo>\n  <mrow>\n    <mi data-mjx-variant=\"-tex-calligraphic\" mathvariant=\"script\">R</mi>\n  </mrow>\n  <mo>,</mo>\n  <mi mathvariant=\"bold-italic\">n</mi>\n  <mo>,</mo>\n  <mi mathvariant=\"bold-italic\">N</mi>\n  <mo stretchy=\"false\">)</mo>\n  <mi>p</mi>\n  <mrow data-mjx-texclass=\"INNER\">\n    <mo data-mjx-texclass=\"OPEN\">(</mo>\n    <msup>\n      <mi mathvariant=\"bold-italic\">R</mi>\n      <mrow>\n        <mo>+</mo>\n      </mrow>\n    </msup>\n    <mo>\u2223</mo>\n    <mi mathvariant=\"bold-italic\">I</mi>\n    <mo data-mjx-texclass=\"CLOSE\">)</mo>\n  </mrow>\n</math>",
        "latex": "p\\left(\\boldsymbol{I}, \\boldsymbol{R}^{+} \\mid \\mathcal{R}, \\boldsymbol{n}, \\boldsymbol{N}\\right)=p(\\boldsymbol{I} \\mid \\mathcal{R}, \\boldsymbol{n}, \\boldsymbol{N}) p\\left(\\boldsymbol{R}^{+} \\mid \\boldsymbol{I}\\right)"
    },
    {
        "id": "7c43d9c3-6b93-4310-a391-61291c04f44b",
        "mathml": "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n  <mn>11</mn>\n  <mo stretchy=\"false\">(</mo>\n  <mn>20.0</mn>\n  <mi mathvariant=\"normal\">%</mi>\n  <mo stretchy=\"false\">)</mo>\n  <mstyle scriptlevel=\"0\">\n    <mspace width=\"1em\"></mspace>\n  </mstyle>\n  <mn>0.0030</mn>\n  <msubsup>\n    <mn>.154</mn>\n    <mrow>\n      <mn>1</mn>\n    </mrow>\n    <mrow>\n      <mo>&lt;</mo>\n      <mn>0.00</mn>\n    </mrow>\n  </msubsup>\n  <mn>0.035</mn>\n</math>",
        "latex": "11(20.0 \\%) \\quad 0.0030 .154_{1}^{<0.00} 0.035"
    }
]