name: Rust

defaults:
  run:
    working-directory: skema/skema-rs

on:
  push:
    branches: [ "main" ]
    paths: 
    - 'skema/skema-rs/**'
  pull_request:
    branches: [ "main" ]
    paths: 
    - 'skema/skema-rs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
